### Home - Check if API is live
GET https://ecom-api-lcxh.onrender.com/
### Get All Categories
GET https://ecom-api-lcxh.onrender.com/api/categories
### Get All Products 
GET https://ecom-api-lcxh.onrender.com/api/products
### Create a new Category
POST https://ecom-api-lcxh.onrender.com/api/categories
Content-Type: application/json

{
  "name": "Furniture",
  "description": "Tables, chairs, sofas and home furniture"
}

### Create a new Product
POST https://ecom-api-lcxh.onrender.com/api/products
Content-Type: application/json

{
  "name": "Blender",
  "description": "A high-speed kitchen blender",
  "price": 2500.00,
  "stock": 8,
  "category": "6919cb7f6f307bafa9270d22",
  "weight": 45000,
  "dimensions": "200x90x95 cm",
  "sku": "BLD-4500X"
}
### Get Single Product (replace ID)
GET https://ecom-api-lcxh.onrender.com/api/products/
### Update Product - Full replace (PUT)
PUT https://ecom-api-lcxh.onrender.com/api/products/6919cb126f307bafa9270d1a
Content-Type: application/json

{
  "name": "New-Chair",
  "category": "6919ecab146009fa148f39e1",
}
### Update Product - Partial (PATCH) - optional if you added PATCH route
PATCH https://ecom-api-lcxh.onrender.com/api/products/REPLACE_WITH_PRODUCT_ID
Content-Type: application/json

{
  "price": 2599.99,
  "stock": 12
}

### Delete Product
DELETE https://ecom-api-lcxh.onrender.com/api/products/6919c09de5e13711d2f236a1
### Delete Category
DELETE https://ecom-api-lcxh.onrender.com/api/categories/