### Get All Categories
GET http://localhost:3000/api/categories
### Create Category
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "name": "test-delete",
  "description": "This is a test category for deletion"
}
### Get Single Category
GET http://localhost:3000/api/categories/6919c090e5e13711d2f2369f
### Update Category
PUT http://localhost:3000/api/categories/691d7c50dc67ba35460f65e1
Content-Type: application/json

{
  "name": "Updated",
  "description": "Updated description for devices and gadgets"
}
### Delete Category
DELETE http://localhost:3000/api/categories/691d7c50dc67ba35460f65e1



### Get All Products
GET http://localhost:3000/api/products
### Create Product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Rich daddy poor daddy",
  "description": "A book about financial education",
  "price": 100,
  "stock": 5,
  "category": "6919cb626f307bafa9270d20",
  "weight": 10000
}
### Update Product (PUT)
PUT http://localhost:3000/api/products/6919cb126f307bafa9270d1a
Content-Type: application/json

{
  "name": "Chair",
  "description": "Comfortable wooden chair",
  "price": 100,
  "stock": 5,
  "category": "6919ecab146009fa148f39e1",
  "weight": 10000
}
### Delete Product
DELETE http://localhost:3000/api/products/6918b12aa7e8e5cc95fb7f92
